Simple calory app
kiindmanjio/ruby-practice pull request #1
Opened 2017-06-27 12:03 UTC by kiindmanjio

#WHAT 
developed a simple calory calculation app.

#WHY 
In order to make it simple for those who want to calculate the caloric input.

2017-06-28 04:34 UTC, offich requested changes

2017-06-28 04:34 UTC, r-ume commented on ruby.rb
> +    return @name
rubyでは、returnは書かないようにしよう。

2017-06-28 04:34 UTC, r-ume commented on ruby.rb
> +    return @calory
ここでも

2017-06-28 04:37 UTC, offich requested changes
レビュしました〜

2017-06-28 04:37 UTC, r-ume commented on ruby.rb
> +  def initialize(name,calory)
initialize メソッドは、一番上にかこう

2017-06-28 04:40 UTC, r-ume commented
あと、PRの概要で、# のマークは、スペースを空けるようにしよう。

2017-06-28 05:27 UTC, kiindmanjio commented on ruby.rb
> +    return @name
そうなの?!笑
rubyのルール??

2017-06-28 05:27 UTC, kiindmanjio commented on ruby.rb
> +  def initialize(name,calory)
これもルール???

2017-06-29 01:25 UTC, kiindmanjio commented
# WHAT
 -deleted return 
 -Changed the position of initialize method to the uppermost of Food class.
# WHY 
Is it because it is the rule of ruby??
if would be great if you can answer my question.

2017-06-29 02:07 UTC, r-ume commented on ruby.rb
> +    return @name
そうだね。受講生には、わかりやすく、returnを使うことを教えているけど、rubyはreturn いらない言語仕様だから、覚えておいて笑

2017-06-29 02:07 UTC, r-ume commented on ruby.rb
> +  def initialize(name,calory)
単純に、コンストラクタは、一番上に書かれているから笑
英語でいうと、He am って言わないでしょ？笑

2017-06-29 02:08 UTC, r-ume commented
↑　上の　whatとかwhyは、一番上を更新すれば、大丈夫。

2017-06-29 02:09 UTC, kiindmanjio commented
なるほど了解です！

2017-06-29 02:12 UTC, r-ume commented on ruby.rb
> +      all_calory = all_calory + food.calory
これは、 `all_calory += food.calory`って書こうか。

2017-06-29 02:13 UTC, offich requested changes
あとちょっと〜

2017-06-29 02:13 UTC, r-ume commented on ruby.rb
> +      all_calory = all_calory + food.calory
これは、`all_calory += food.calory` って書こうか

2017-06-29 02:13 UTC, r-ume commented on ruby.rb
> +
余行は削除しましょ

2017-06-29 03:02 UTC, kiindmanjio commented
<質問>
・return を使わないのはrubyのルール??
・initializeメソッドを初めに書くのはrubyのルール??

修正done
お願いします！！

2017-06-29 03:08 UTC, r-ume commented
あ、上の質問は、じおが質問したのところに書いてる

2017-06-29 03:16 UTC, kiindmanjio commented
おー！確認できた！

2017-06-29 03:17 UTC, r-ume commented
LGTM

2017-06-29 03:18 UTC, merged